-- 코드를 입력하세요
SELECT A.CAR_ID, A.CAR_TYPE, TRUNCATE(A.DAILY_FEE*(100-DISCOUNT_RATE)/100*30,0) AS FEE
FROM CAR_RENTAL_COMPANY_CAR A JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY B on A.CAR_ID=B.CAR_ID join CAR_RENTAL_COMPANY_DISCOUNT_PLAN C on A.CAR_TYPE=C.CAR_TYPE
WHERE A.CAR_TYPE in("세단","SUV") and C.DURATION_TYPE = '30일 이상'
GROUP BY A.CAR_ID
HAVING MAX(B.END_DATE) < "2022-11-01" and FEE BETWEEN 500000 and 2000000
ORDER BY 3 DESC,2 ASC,1 DESC;